# Golden fixture: statnet `tergm` CMPLE + a btergm-style block bootstrap on a
# simulated 8-wave directed panel.
#
# Regenerate from the package root (~60s):
#
#   Rscript test/fixtures/r/panel_stergm.R > test/fixtures/panel_stergm.toml
#
# WHAT IS BEING VALIDATED, AND WHY THE PANEL IS DYAD-INDEPENDENT ON PURPOSE
#
# TERGM.jl's `stergm(...; method=:cmple)` fits a SEPARABLE model by conditional
# pseudo-likelihood: formation rows are the dyads that were non-edges at t-1
# (statistics on Y+ = Y_{t-1} u Y_t), persistence rows are the dyads that were
# edges at t-1 (statistics on Y- = Y_{t-1} n Y_t), pooled over transitions and
# maximized by logistic regression. R's `tergm(..., estimate="CMPLE")` is the
# same estimator, written by other people.
#
# The formation and persistence formulas here are edges + nodematch("grp"), which
# are DYAD-INDEPENDENT. That is deliberate, and it is what gives the fixture
# teeth: under dyad independence the conditional pseudo-likelihood IS the
# conditional likelihood, so CMPLE is the exact conditional MLE. Both packages
# maximize the same strictly-concave logistic likelihood; there is no Monte Carlo
# on either side. Agreement is asserted at 1e-6, and a failure is a BUG -- in the
# auxiliary-network construction, in the free-dyad selection, or in a change
# statistic -- not noise. A dyad-dependent formula would have bought a prettier
# model and destroyed the ability to say anything exact.
#
# The panel is generated by an explicit discrete-time separable Markov chain
# (below) rather than by tergm's simulator: with dyad-independent terms the STERGM
# transition kernel factorizes into independent per-dyad Bernoulli draws, so these
# eight waves ARE an exact draw from the model being fitted, and the generating
# code is three lines of `rbinom` rather than a second implementation whose bugs
# could cancel with the estimator's. The waves are frozen into the fixture as edge
# lists, so the Julia side fits the identical networks and re-simulates nothing.
#
# THE BLOCK BOOTSTRAP
#
# TERGM.jl's `se=:bootstrap` resamples TRANSITIONS with replacement and refits.
# That is btergm's scheme: `btergm::btergm` calls `boot(unique.time.steps,
# estimate, R = R)` -- it resamples time steps, not dyads. btergm itself cannot be
# pointed at a separable Form/Persist model (it fits a pooled, non-separable
# TERGM), so this script applies btergm's resampling scheme to the CMPLE design
# directly: draw transition indices with replacement, keep the pseudo-likelihood
# rows belonging to the drawn transitions, refit by `glm`, take the empirical
# covariance of the replicate coefficients.
#
# That means the bootstrap is run over a design matrix built in this script rather
# than inside tergm, which would be worth nothing if the design were wrong -- so
# the script CHECKS it: `cmple_vs_glm_max_abs_diff` in [values] is the largest
# discrepancy between `tergm(estimate="CMPLE")`'s coefficients and the glm's on the
# same panel. It is ~1e-9. The rows being resampled are therefore tergm's rows.
#
# A bootstrap standard error is itself a random variable: the two packages draw
# DIFFERENT resamples, and can never agree to machine precision no matter how
# correct both are. So the script reruns the entire bootstrap under five further
# seeds and freezes the seed-to-seed sd of every bootstrap SE (`boot_se_seed_sd`).
# The tolerance is a multiple of that measured width. Comparing two bootstraps any
# other way would be measuring nothing.
#
# THE BOUNDARY PANEL (second, small panel; keys `boundary_*`)
#
# A statistic at the boundary of its attainable range -- here a persistence
# nodematch("grp") on a panel in which NO same-group tie ever persists -- has no
# finite CMPLE. R ergm's `drop=TRUE` fixes such a coefficient at -Inf and fits the
# rest on the dyads the statistic does not touch; TERGM.jl does exactly that (it
# runs ERGM.jl's MPLE design fitter). R tergm 4.2.2 does NOT: its Form()/Persist()
# operator terms bypass ergm's attainable-range check, so it warns "The MPLE does
# not exist!" and returns whatever point glm's default stopping rule reached on
# the flat asymptote (about -19.6 with a standard error of 1600). That number is
# an artefact of glm's epsilon, not an estimate, and is frozen here ONLY as a
# record (`boundary_coefficients`); what the fixture ASSERTS is everything that IS
# a number: the finite coefficients (identical in both packages, because the
# asymptote's rows contribute nothing to them), their standard errors, the
# log-likelihood, R's warning text, and R's logLik df/nobs attributes.

suppressMessages({
  .libPaths(c(path.expand("~/R/library"), .libPaths()))
  library(network)
  library(tergm)
  library(btergm)
})

seed <- 20260713
set.seed(seed)

n_actors <- 25
n_waves <- 8

# Alternating two-group attribute: 13 "a", 12 "b".
grp <- rep(c("a", "b"), length.out = n_actors)
same <- outer(grp, grp, "==")
diag(same) <- FALSE

logistic <- function(x) 1 / (1 + exp(-x))

# Separable dyad-independent STERGM transition kernel. theta_form governs whether
# a non-tie appears; theta_persist whether a tie survives. Both are
# edges + nodematch("grp").
theta_form <- c(edges = -2.2, nodematch.grp = 0.8)
theta_persist <- c(edges = 0.5, nodematch.grp = 0.9)

P_form <- logistic(theta_form[1] + theta_form[2] * same)
P_persist <- logistic(theta_persist[1] + theta_persist[2] * same)

offdiag <- which(row(matrix(0, n_actors, n_actors)) !=
                 col(matrix(0, n_actors, n_actors)))

M <- matrix(0L, n_actors, n_actors)
M[offdiag] <- rbinom(length(offdiag), 1, 0.10)   # wave 1: Bernoulli(0.10)
mats <- list(M)
for (t in 2:n_waves) {
  U <- matrix(runif(n_actors * n_actors), n_actors, n_actors)
  N <- ifelse(M == 1L, as.integer(U < P_persist), as.integer(U < P_form))
  diag(N) <- 0L
  mats[[t]] <- N
  M <- N
}

as_nw <- function(A) {
  nw <- network(A, directed = TRUE)
  nw %v% "grp" <- grp
  nw
}
nets <- lapply(mats, as_nw)

# --- (1) tergm CMPLE ---------------------------------------------------------
# tergm prints "Starting maximum pseudolikelihood estimation (MPLE)..." to stdout,
# and this script's stdout IS the TOML fixture, so unsuppressed it emits an
# unparseable file.
fit <- NULL
invisible(capture.output(
  fit <- tergm(nets ~ Form(~edges + nodematch("grp")) +
                      Persist(~edges + nodematch("grp")),
               estimate = "CMPLE", times = 1:n_waves),
  type = "output"))
cmple_coef <- coef(fit)
cmple_se <- sqrt(diag(vcov(fit)))

# --- (2) the CMPLE design, per transition, for the block bootstrap -----------
# Formation rows: dyads that were 0 at t-1. Persistence rows: dyads that were 1.
# Response is the tie at t. Predictors for edges + nodematch("grp") are (1, same),
# which under dyad independence is exactly the change statistic on Y+ / Y-.
blocks <- lapply(2:n_waves, function(t) {
  prev <- mats[[t - 1]]; cur <- mats[[t]]
  fi <- which(prev == 0 & row(prev) != col(prev))
  di <- which(prev == 1)
  list(Xf = cbind(1, as.numeric(same[fi])), yf = as.numeric(cur[fi]),
       Xd = cbind(1, as.numeric(same[di])), yd = as.numeric(cur[di]))
})

# `ctrl` is the convergence criterion. The DEFAULT (epsilon = 1e-8) is what
# tergm ships; the tight one (1e-14) pins down where the exact conditional MLE
# actually is. The difference between them turns out to matter -- see below.
fit_blocks <- function(idx, ctrl = glm.control()) {
  Xf <- do.call(rbind, lapply(idx, function(b) blocks[[b]]$Xf))
  yf <- unlist(lapply(idx, function(b) blocks[[b]]$yf))
  Xd <- do.call(rbind, lapply(idx, function(b) blocks[[b]]$Xd))
  yd <- unlist(lapply(idx, function(b) blocks[[b]]$yd))
  gf <- glm.fit(Xf, yf, family = binomial(), control = ctrl)
  gd <- glm.fit(Xd, yd, family = binomial(), control = ctrl)
  se <- function(g) sqrt(diag(chol2inv(g$qr$qr[1:g$rank, 1:g$rank, drop = FALSE])))
  list(coef = c(gf$coefficients, gd$coefficients), se = c(se(gf), se(gd)))
}

n_trans <- n_waves - 1
tight <- glm.control(epsilon = 1e-14, maxit = 200)
glm_tight <- fit_blocks(seq_len(n_trans), tight)

# THE CHECK THAT MAKES THE BOOTSTRAP MEAN ANYTHING: does the design matrix built
# in this script reproduce tergm's own CMPLE fit? If not, the bootstrap below is
# resampling the wrong rows and the fixture is worthless.
#
# It does -- and in the process it exposes something worth freezing. tergm's
# CMPLE runs R's `glm` at its DEFAULT convergence criterion (epsilon = 1e-8) and
# stops there, ~1.5e-8 short of the exact conditional MLE in the coefficients and
# ~6e-6 short in the standard errors (the SEs are the more sensitive of the two,
# being a function of the fitted probabilities). TERGM.jl runs Newton-Raphson to
# tol = 1e-8 in the gradient and lands on the EXACT optimum, reproducing the
# tightly-converged R glm to ~1e-10.
#
# So the residual disagreement between TERGM.jl and tergm on this model is
# tergm's optimizer slack, not TERGM.jl's error. Both numbers are frozen: the
# `coefficients`/`std_errors` values are tergm's as-shipped output, and the
# `exact_*` values are the same estimator taken to convergence. The Julia testset
# asserts against BOTH, tightly against the exact one.
cmple_vs_glm <- max(abs(as.numeric(cmple_coef) - glm_tight$coef))
cmple_se_vs_glm <- max(abs(as.numeric(cmple_se) - glm_tight$se))

# --- (3) btergm-style block bootstrap over transitions -----------------------
R_boot <- 400
boot_once <- function(s) {
  set.seed(s)
  reps <- t(replicate(R_boot,
                      fit_blocks(sample(seq_len(n_trans), n_trans,
                                        replace = TRUE))$coef))
  apply(reps, 2, sd)
}
boot_se <- boot_once(seed)

# How much does the bootstrap SE move when only the RESAMPLE DRAWS change?
boot_seeds <- c(101, 202, 303, 404, 505)
boot_reps <- t(sapply(boot_seeds, boot_once))
boot_se_sd <- apply(boot_reps, 2, sd)

# --- (4) the boundary panel: no same-group tie ever persists ------------------
# Seeded on its own so the main panel above is untouched whatever is added here.
boundary_seed <- 20260912
set.seed(boundary_seed)
b_n <- 8
b_waves <- 3
b_grp <- rep(c("a", "b"), length.out = b_n)
b_same <- outer(b_grp, b_grp, "==")
diag(b_same) <- FALSE
b_offd <- row(b_same) != col(b_same)
B <- matrix(0L, b_n, b_n)
B[b_offd] <- rbinom(sum(b_offd), 1, 0.35)
b_mats <- list(B)
for (t in 2:b_waves) {
  N <- matrix(0L, b_n, b_n)
  for (i in 1:b_n) for (j in 1:b_n) if (i != j) {
    if (B[i, j] == 1L) {
      # a same-group tie NEVER persists (the boundary); cross-group ties do, at 0.6
      N[i, j] <- if (b_same[i, j]) 0L else rbinom(1, 1, 0.6)
    } else {
      N[i, j] <- rbinom(1, 1, 0.3)
    }
  }
  b_mats[[t]] <- N
  B <- N
}
b_nets <- lapply(b_mats, function(A) {
  nw <- network(A, directed = TRUE)
  nw %v% "grp" <- b_grp
  nw
})
b_fit <- NULL
b_warnings <- character(0)
invisible(capture.output(
  b_fit <- withCallingHandlers(
    tergm(b_nets ~ Form(~edges + nodematch("grp")) +
                   Persist(~edges + nodematch("grp")),
          estimate = "CMPLE", times = 1:b_waves),
    warning = function(w) {
      b_warnings <<- c(b_warnings, conditionMessage(w))
      invokeRestart("muffleWarning")
    }),
  type = "output"))
b_coef <- coef(b_fit)
b_se <- sqrt(diag(vcov(b_fit)))
b_ll <- logLik(b_fit)

# The exact limit of the pseudo-likelihood (R ergm's drop): formation on all its
# rows, persistence on the rows the dropped statistic does not touch (the
# cross-group prior ties, nodematch == 0), both by glm taken to convergence.
b_blocks <- lapply(2:b_waves, function(t) {
  prev <- b_mats[[t - 1]]; cur <- b_mats[[t]]
  fi <- which(prev == 0 & b_offd)
  di <- which(prev == 1)
  list(Xf = cbind(1, as.numeric(b_same[fi])), yf = as.numeric(cur[fi]),
       Xd = cbind(1, as.numeric(b_same[di])), yd = as.numeric(cur[di]))
})
b_Xf <- do.call(rbind, lapply(b_blocks, `[[`, "Xf")); b_yf <- unlist(lapply(b_blocks, `[[`, "yf"))
b_Xd <- do.call(rbind, lapply(b_blocks, `[[`, "Xd")); b_yd <- unlist(lapply(b_blocks, `[[`, "yd"))
stopifnot(sum(b_yd[b_Xd[, 2] == 1]) == 0)      # the boundary: no same-group tie persists
stopifnot(sum(b_Xd[, 2] == 1) > 0)             # ... and there were same-group ties to lose
b_keep <- b_Xd[, 2] == 0
b_se_of <- function(g) sqrt(diag(chol2inv(g$qr$qr[1:g$rank, 1:g$rank, drop = FALSE])))
b_gf <- glm.fit(b_Xf, b_yf, family = binomial(), control = tight)
b_gd <- glm.fit(b_Xd[b_keep, 1, drop = FALSE], b_yd[b_keep], family = binomial(),
                control = tight)
b_exact_coef <- c(b_gf$coefficients, b_gd$coefficients)      # Form~edges, Form~nodematch, Persist~edges
b_exact_se <- c(b_se_of(b_gf), b_se_of(b_gd))
b_finite <- c(1, 2, 3)                                         # indices of the finite coefficients
b_dropped_ll <- -sum(b_gf$deviance, b_gd$deviance) / 2         # loglik of the exact limit
# How much of R's logLik is the asymptote's tail: the dropped rows at tergm's
# finite asymptote point contribute sum(log(1 - p)) with p = logistic(eta) ~ 1e-8.
b_eta_dropped <- b_coef[3] + b_coef[4]
b_tail <- sum(b_Xd[, 2] == 1) * log(1 - plogis(b_eta_dropped))
b_cmple_vs_glm <- max(abs(as.numeric(b_coef)[b_finite] - b_exact_coef))
b_cmple_se_vs_glm <- max(abs(as.numeric(b_se)[b_finite] - b_exact_se))
b_edge_arrays <- function(sel) paste(sapply(b_mats, function(A) {
  e <- which(A == 1L, arr.ind = TRUE)
  paste0("[", paste(e[, sel], collapse = ", "), "]")
}), collapse = ", ")

# --- (5) dyad-dependent CMPLE on the main panel, and an undirected panel ------
# The main panel's formula is dyad-independent so that agreement can be called
# exact. But tergm's CMPLE for DYAD-DEPENDENT terms (mutual, triangle) and for
# UNDIRECTED panels is the same estimator written by other people, and until
# 2026-09 nothing in the repo pinned it: the on-Y+/Y- change-statistic
# evaluation of a dependent term and the n(n-1)/2 undirected free-dyad
# enumeration were tested only against themselves. These fits are frozen as
# tergm ships them (glm at its default epsilon), so the tolerances are the
# main panel's as-shipped ones: 1e-6 on coefficients, 1e-4 on standard errors
# (both far above the ~1e-8 / ~6e-6 optimizer slack measured above and far
# below any real discrepancy). Under dyadic dependence the CMPLE is an
# approximation to the CMLE -- but it is a deterministic function of the panel
# and the change statistics, so two correct implementations agree on it to the
# optimizer's slack, exactly as for the independent formula. Nothing is
# asserted about the model's adequacy, only that the two packages fit the same
# pseudo-likelihood.
fit_quiet <- function(expr) {
  f <- NULL
  w <- character(0)
  invisible(capture.output(
    f <- withCallingHandlers(expr, warning = function(cond) {
      w <<- c(w, conditionMessage(cond))
      invokeRestart("muffleWarning")
    }),
    type = "output"))
  ll <- logLik(f)
  list(coef = as.numeric(coef(f)), se = sqrt(diag(vcov(f))),
       names = names(coef(f)), loglik = as.numeric(ll),
       df = attr(ll, "df"), nobs = attr(ll, "nobs"), warnings = unique(w))
}
dd_mutual <- fit_quiet(tergm(nets ~ Form(~edges + mutual) + Persist(~edges + mutual),
                             estimate = "CMPLE", times = 1:n_waves))
dd_triangle <- fit_quiet(tergm(nets ~ Form(~edges + triangle) + Persist(~edges),
                               estimate = "CMPLE", times = 1:n_waves))
stopifnot(length(dd_mutual$warnings) == 0, length(dd_triangle$warnings) == 0)

# The undirected panel: 14 actors, 5 waves, alternating two-group `grp`,
# drawn from a separable chain with homophilous formation and a persistence
# that does not depend on triangles (so Persist~triangle is a genuine
# dyad-dependent CMPLE on a model that does not generate it -- a fit, not a
# recovery). Symmetric matrices; the upper triangle is what is frozen.
u_seed <- 20260913
set.seed(u_seed)
u_n <- 14
u_waves <- 5
u_grp <- rep(c("a", "b"), length.out = u_n)
u_same <- outer(u_grp, u_grp, "==")
u_upper <- upper.tri(matrix(0, u_n, u_n))
sym <- function(U) { U[lower.tri(U)] <- t(U)[lower.tri(U)]; diag(U) <- 0L; U }
U <- matrix(0L, u_n, u_n)
U[u_upper] <- rbinom(sum(u_upper), 1, 0.22)
U <- sym(U)
u_mats <- list(U)
for (t in 2:u_waves) {
  N <- matrix(0L, u_n, u_n)
  for (i in 1:(u_n - 1)) for (j in (i + 1):u_n) {
    N[i, j] <- if (U[i, j] == 1L) rbinom(1, 1, if (u_same[i, j]) 0.75 else 0.6)
               else rbinom(1, 1, if (u_same[i, j]) 0.18 else 0.08)
  }
  N <- sym(N)
  u_mats[[t]] <- N
  U <- N
}
u_nets <- lapply(u_mats, function(A) {
  nw <- network(A, directed = FALSE)
  nw %v% "grp" <- u_grp
  nw
})
stopifnot(all(sapply(u_nets, function(nw) !is.directed(nw))))
undir <- fit_quiet(tergm(u_nets ~ Form(~edges + nodematch("grp")) + Persist(~edges + triangle),
                         estimate = "CMPLE", times = 1:u_waves))
undir_kstar <- fit_quiet(tergm(u_nets ~ Form(~edges + kstar(2)) + Persist(~edges),
                               estimate = "CMPLE", times = 1:u_waves))
stopifnot(length(undir$warnings) == 0, length(undir_kstar$warnings) == 0)
# The undirected free-dyad count: n(n-1)/2 unordered dyads per transition
stopifnot(undir$nobs == (u_waves - 1) * u_n * (u_n - 1) / 2)
u_edge_arrays <- function(sel) paste(sapply(u_mats, function(A) {
  e <- which(A == 1L & upper.tri(A), arr.ind = TRUE)
  paste0("[", paste(e[, sel], collapse = ", "), "]")
}), collapse = ", ")

# --- (6) expanding terms: nodefactor / nodemix / degree ranges ---------------
# statnet resolves nodefactor("grp") into one column per non-base level,
# nodemix("grp") into one per selected cell and degree(0:2) into one per
# degree at model construction, and tergm's Form()/Persist() operators inherit
# that. TERGM.jl skipped ERGM.jl's expansion step until 2026-09 round 3 and
# pooled every level into ONE column under a label R never prints (a silently
# different model, not a numerical discrepancy). These four fits pin the
# expansion under R's labels: the column set, its order (statnet's cell order
# for nodemix), and the coefficients on both a directed and an undirected
# panel. A three-level attribute on the undirected panel exercises the
# multi-level case; the main panel's two-level `grp` gives directed nodemix
# its three cells (b.a, a.b, b.b -- a.a dropped). Frozen as tergm ships them,
# compared at the as-shipped tolerances (1e-6 / 1e-4 / 1e-5).
u_grp3 <- rep(c("a", "b", "c"), length.out = u_n)
u_nets3 <- lapply(u_mats, function(A) {
  nw <- network(A, directed = FALSE)
  nw %v% "grp3" <- u_grp3
  nw
})
expand_undirected <- fit_quiet(tergm(u_nets3 ~ Form(~edges + nodefactor("grp3")) +
                                                Persist(~edges + nodemix("grp3")),
                                     estimate = "CMPLE", times = 1:u_waves))
expand_undirected_degree <- fit_quiet(tergm(u_nets3 ~ Form(~edges + degree(1:2)) +
                                                       Persist(~edges + degree(0:1)),
                                            estimate = "CMPLE", times = 1:u_waves))
expand_directed <- fit_quiet(tergm(nets ~ Form(~edges + nodefactor("grp")) +
                                          Persist(~edges + nodemix("grp")),
                                   estimate = "CMPLE", times = 1:n_waves))
expand_directed_degree <- fit_quiet(tergm(nets ~ Form(~edges + nodemix("grp")) +
                                                 Persist(~edges + odegree(0:1)),
                                          estimate = "CMPLE", times = 1:n_waves))
stopifnot(length(expand_undirected$warnings) == 0,
          length(expand_undirected_degree$warnings) == 0,
          length(expand_directed$warnings) == 0,
          length(expand_directed_degree$warnings) == 0)
# The expansion itself, as R resolved it: 2 nodefactor + 5 nodemix columns
# undirected, 1 nodefactor + 3 nodemix columns directed
stopifnot(length(expand_undirected$coef) == 9, length(expand_directed$coef) == 6,
          length(expand_undirected_degree$coef) == 6, length(expand_directed_degree$coef) == 7)

num <- function(x) paste(sprintf("%.17g", x), collapse = ", ")
strs <- function(x) paste(sprintf('"%s"', x), collapse = ", ")
edge_arrays <- function(sel) paste(sapply(mats, function(A) {
  e <- which(A == 1L, arr.ind = TRUE)
  paste0("[", paste(e[, sel], collapse = ", "), "]")
}), collapse = ", ")

cat('name = "panel_stergm"\n\n')

cat("[provenance]\n")
cat(sprintf('r_version = "%s"\n', as.character(getRversion())))
cat(sprintf('tergm_version = "%s"\n', as.character(packageVersion("tergm"))))
cat(sprintf('btergm_version = "%s"\n', as.character(packageVersion("btergm"))))
cat(sprintf('ergm_version = "%s"\n', as.character(packageVersion("ergm"))))
cat(sprintf('network_version = "%s"\n', as.character(packageVersion("network"))))
cat(sprintf("seed = %d\n", seed))
cat('script = "test/fixtures/r/panel_stergm.R"\n')
cat(sprintf('date = "%s"\n', format(Sys.Date())))
cat('dataset = "simulated: 25 actors, 8 directed waves, alternating two-group `grp` attribute; drawn from the separable dyad-independent STERGM whose parameters are in [values].generating_* -- the waves themselves are frozen below, nothing is re-simulated in Julia"\n')
cat('model = "Form(~edges + nodematch(\\"grp\\")) + Persist(~edges + nodematch(\\"grp\\")), estimate=\\"CMPLE\\", times=1:8"\n')
cat(sprintf('bootstrap = "btergm-style block bootstrap: %d resamples of the %d transitions with replacement, refit by glm"\n', R_boot, n_trans))
cat(sprintf('bootstrap_seeds = "%s"\n', paste(boot_seeds, collapse = ",")))
cat(sprintf("boundary_seed = %d\n", boundary_seed))
cat('boundary_dataset = "simulated: 8 actors, 3 directed waves, alternating two-group `grp`; every same-group tie dissolves at the next wave (persistence nodematch at its smallest attainable value), cross-group ties persist at 0.6, formation at 0.3"\n')
cat('boundary_model = "Form(~edges + nodematch(\\"grp\\")) + Persist(~edges + nodematch(\\"grp\\")), estimate=\\"CMPLE\\", times=1:3"\n')
cat('dyaddep_models = "on the main panel: Form(~edges + mutual) + Persist(~edges + mutual) and Form(~edges + triangle) + Persist(~edges), estimate=\\"CMPLE\\", times=1:8"\n')
cat(sprintf("undirected_seed = %d\n", u_seed))
cat('undirected_dataset = "simulated: 14 actors, 5 UNDIRECTED waves, alternating two-group `grp`; drawn from a separable chain (formation 0.18 same-group / 0.08 cross, persistence 0.75 / 0.6); the upper triangles are frozen below"\n')
cat('undirected_models = "Form(~edges + nodematch(\\"grp\\")) + Persist(~edges + triangle) and Form(~edges + kstar(2)) + Persist(~edges), estimate=\\"CMPLE\\", times=1:5"\n')
cat('expand_models = "expanding terms under R labels: on the undirected panel with a three-level `grp3` (a,b,c repeating), Form(~edges + nodefactor(\\"grp3\\")) + Persist(~edges + nodemix(\\"grp3\\")) and Form(~edges + degree(1:2)) + Persist(~edges + degree(0:1)); on the main directed panel Form(~edges + nodefactor(\\"grp\\")) + Persist(~edges + nodemix(\\"grp\\")) and Form(~edges + nodemix(\\"grp\\")) + Persist(~edges + odegree(0:1)); estimate=\\"CMPLE\\""\n')
cat("\n")

cat("[tolerance]\n")
cat("# CMPLE COEFFICIENTS AND STANDARD ERRORS. edges + nodematch is\n")
cat("# dyad-independent, so the conditional pseudo-likelihood IS the conditional\n")
cat("# likelihood: CMPLE is the exact conditional MLE and both packages are\n")
cat("# maximizing the same strictly-concave logistic likelihood on the same rows.\n")
cat("# No Monte Carlo, no approximation, nothing to average over. The ONLY\n")
cat("# difference two correct implementations can have here is where their\n")
cat("# optimizers stop -- and on this model that difference is measurable, and it\n")
cat("# is R's, not Julia's:\n")
cat("#\n")
cat("#   tergm's CMPLE runs R's `glm` at its default epsilon = 1e-8 and stops\n")
cat("#   there. Against the same glm taken to epsilon = 1e-14, tergm's shipped\n")
cat("#   answer is off by ~1.5e-8 in the coefficients and ~6e-6 in the standard\n")
cat("#   errors (the SEs are the more sensitive of the two, being a function of\n")
cat("#   the fitted probabilities). TERGM.jl's Newton-Raphson lands on the exact\n")
cat("#   optimum and reproduces the tightly-converged R glm to ~1e-10.\n")
cat("#\n")
cat("# So `coefficients`/`std_errors` are compared to tergm AS SHIPPED at a\n")
cat("# tolerance that covers tergm's own optimizer slack -- 1e-6 on the\n")
cat("# coefficients (60x the observed slack) and 1e-4 on the standard errors\n")
cat("# (16x the observed slack, and still 0.13% of the smallest SE in the model,\n")
cat("# far too tight for any real discrepancy to hide under). Widening the SE\n")
cat("# tolerance is not a concession: `exact_std_errors` below is the same\n")
cat("# estimator taken to convergence, and THAT is asserted at 1e-6, where\n")
cat("# TERGM.jl passes with four orders of magnitude to spare. The loose number\n")
cat("# measures R; the tight number measures Julia.\n")
cat("coefficients = 1e-6\n")
cat("std_errors = 1e-4\n")
cat("exact_coefficients = 1e-6\n")
cat("exact_std_errors = 1e-6\n")
cat("# The per-side vectors are the same numbers split by side (`Form(1)~` rows\n")
cat("# into `formation_*`, `Persist(1)~` rows into `persistence_*`) and carry the\n")
cat("# same tolerances: they exist so that the accessors `formation_coef(fit)`,\n")
cat("# `formation_se(fit)`, `persistence_coef(fit)`, `persistence_se(fit)` can be\n")
cat("# pinned BY NAME against tergm's Persist() block (the persistence sign\n")
cat("# convention: tergm >= 4 Persist(), positive = ties last longer).\n")
cat("formation_coefficients = 1e-6\n")
cat("formation_std_errors = 1e-4\n")
cat("persistence_coefficients = 1e-6\n")
cat("persistence_std_errors = 1e-4\n")
cat("#\n")
cat("# BLOCK-BOOTSTRAP STANDARD ERRORS. A bootstrap SE is a random variable: R\n")
cat("# and Julia draw different resamples of the transitions, so they cannot\n")
cat("# agree to machine precision however correct both are. Read\n")
cat("# `boot_se_seed_sd` in [values] first -- that is THIS bootstrap, rerun under\n")
cat("# five further seeds, disagreeing with itself. With only 7 transitions to\n")
cat("# resample the block bootstrap is coarse by construction and that sd is\n")
cat("# large relative to the SE itself; no cross-implementation tolerance can\n")
cat("# sit below it. The tolerance is 3x the largest such sd, which is the\n")
cat("# honest resolution of the comparison. It is deliberately NOT used to make\n")
cat("# a claim the data cannot support: what this checks is that TERGM.jl's\n")
cat("# bootstrap SEs agree with R's to within the noise of the bootstrap itself,\n")
cat("# not that they are equal.\n")
cat("#\n")
cat("# Measured on the Julia side (mean of 5 TERGM.jl bootstraps at declared\n")
cat("# seeds, 400 resamples each): |mean(TERGM.jl) - R| = 0.0032, 0.0040,\n")
cat("# 0.0006, 0.0071. TERGM.jl's own seed-to-seed sd is 0.0023, 0.0023, 0.0009,\n")
cat("# 0.0051 -- the same order as R's. The largest gap (0.0071, on persistence\n")
cat("# nodematch) is 1.7x R's seed-to-seed sd on that SE, i.e. the two bootstraps\n")
cat("# differ by about as much as either differs from itself. Both sides are\n")
cat("# seeded, so the Julia comparison is deterministic and cannot flake.\n")
cat(sprintf("boot_std_errors = %.4g\n", 3 * max(boot_se_sd)))
cat("#\n")
cat("# THE BOUNDARY PANEL. The persistence nodematch has no finite CMPLE (no\n")
cat("# same-group tie ever persists). TERGM.jl fixes it at -Inf and fits the rest\n")
cat("# on the untouched rows, as R ergm's drop=TRUE does; tergm 4.2.2 warns\n")
cat("# \"The MPLE does not exist!\" and returns a point on the asymptote. The\n")
cat("# FINITE coefficients are the same estimator on the same rows in both\n")
cat("# packages (the asymptote's rows contribute nothing to them), so they are\n")
cat("# compared exactly as the main panel's: against tergm as shipped at a\n")
cat("# tolerance covering glm's default-epsilon slack (`boundary_cmple_vs_glm_*`\n")
cat("# in [values] measures it), and against the tightly converged glm at 1e-6.\n")
cat("# The log-likelihood differs by the asymptote's tail -- the dropped rows at\n")
cat("# tergm's finite point contribute sum(log(1 - p)) with p ~ 1e-8, frozen as\n")
cat("# `boundary_asymptote_tail` -- plus glm's slack; 1e-5 covers both by two\n")
cat("# orders of magnitude. The infinite coefficient is asserted by SIGN only\n")
cat("# (`boundary_fixed_sign`): R's -19.6 is where glm stopped, not a number.\n")
cat("boundary_finite_coefficients = 1e-6\n")
cat("boundary_finite_std_errors = 1e-4\n")
cat("boundary_exact_finite_coefficients = 1e-6\n")
cat("boundary_exact_finite_std_errors = 1e-6\n")
cat("boundary_loglik = 1e-5\n")
cat("#\n")
cat("# DYAD-DEPENDENT AND UNDIRECTED CMPLE. tergm as shipped (glm at its default\n")
cat("# epsilon), compared at the main panel's as-shipped tolerances: 1e-6 on the\n")
cat("# coefficients and 1e-4 on the standard errors -- two and one orders of\n")
cat("# magnitude above the optimizer slack measured on the main panel (1.5e-8 /\n")
cat("# 6.1e-6), and two orders of magnitude below the smallest standard error\n")
cat("# in any of these models. The log-likelihood at 1e-5 (glm's stopping slack\n")
cat("# in the deviance is ~1e-9). A dyad-dependent CMPLE is a deterministic\n")
cat("# function of the panel and the change statistics, so two correct\n")
cat("# implementations agree on it to the optimizer's slack exactly as they do on\n")
cat("# the independent formula; what these keys pin is the evaluation of mutual /\n")
cat("# triangle / kstar change statistics ON Y+ and Y- and the undirected\n")
cat("# n(n-1)/2 free-dyad enumeration (`undirected_loglik_nobs`), not the\n")
cat("# adequacy of the approximation.\n")
cat("#\n")
cat("# EXPANDING TERMS (nodefactor / nodemix / degree ranges). The same estimator\n")
cat("# on the same rows once the columns are the same, so the as-shipped\n")
cat("# tolerances apply; what these keys pin is that the columns ARE the same --\n")
cat("# `<prefix>_term_names` is asserted verbatim, so a pooled or mislabelled\n")
cat("# expansion fails on the names before any number is compared.\n")
for (k in c("dyaddep_mutual", "dyaddep_triangle", "undirected", "undirected_kstar",
            "expand_undirected", "expand_undirected_degree", "expand_directed",
            "expand_directed_degree")) {
  cat(sprintf("%s_coefficients = 1e-6\n", k))
  cat(sprintf("%s_std_errors = 1e-4\n", k))
  cat(sprintf("%s_loglik = 1e-5\n", k))
}
cat("\n")

cat("[values]\n")
cat("# --- the panel, frozen. Julia rebuilds these exact networks. -------------\n")
cat(sprintf("n_actors = %d\n", n_actors))
cat(sprintf("n_waves = %d\n", n_waves))
cat("directed = true\n")
cat(sprintf("grp = [%s]\n", strs(grp)))
cat(sprintf("edge_counts = [%s]\n", paste(sapply(mats, sum), collapse = ", ")))
cat(sprintf("wave_src = [%s]\n", edge_arrays(1)))
cat(sprintf("wave_dst = [%s]\n", edge_arrays(2)))
cat("\n# The parameters the panel was drawn from. NOT an assertion target -- the\n")
cat("# estimator is being compared to R, not to truth -- but a sanity anchor: a\n")
cat("# fit that lands far from these on 7 transitions of 600 dyads is suspicious.\n")
cat(sprintf("generating_formation = [%s]\n", num(theta_form)))
cat(sprintf("generating_persistence = [%s]\n", num(theta_persist)))
cat("\n# --- tergm CMPLE: exact conditional MLE, compared at 1e-6 ---------------\n")
cat(sprintf("term_names = [%s]\n", strs(names(cmple_coef))))
cat(sprintf("coefficients = [%s]\n", num(as.numeric(cmple_coef))))
cat(sprintf("std_errors = [%s]\n", num(as.numeric(cmple_se))))
cat("# Formation and persistence split out, in TERGM.jl's own accessor order.\n")
cat(sprintf("formation_coefficients = [%s]\n", num(as.numeric(cmple_coef)[1:2])))
cat(sprintf("formation_std_errors = [%s]\n", num(as.numeric(cmple_se)[1:2])))
cat(sprintf("persistence_coefficients = [%s]\n", num(as.numeric(cmple_coef)[3:4])))
cat(sprintf("persistence_std_errors = [%s]\n", num(as.numeric(cmple_se)[3:4])))
cat("\n# --- the SAME estimator, taken to convergence ---------------------------\n")
cat("# R glm at epsilon = 1e-14 rather than tergm's default 1e-8. This is where\n")
cat("# the exact conditional MLE actually is, and it is what TERGM.jl reproduces\n")
cat("# (to ~1e-10). Asserted at 1e-6.\n")
cat(sprintf("exact_coefficients = [%s]\n", num(glm_tight$coef)))
cat(sprintf("exact_std_errors = [%s]\n", num(glm_tight$se)))
cat("\n# How far tergm AS SHIPPED sits from that exact optimum. This is the\n")
cat("# entire residual disagreement between TERGM.jl and tergm on this model:\n")
cat("# it is R's optimizer slack, and it is why `std_errors` above is compared\n")
cat("# at 1e-4 while `exact_std_errors` is compared at 1e-6.\n")
cat(sprintf("cmple_vs_glm_max_abs_diff = %.17g\n", cmple_vs_glm))
cat(sprintf("cmple_se_vs_glm_max_abs_diff = %.17g\n", cmple_se_vs_glm))
cat("\n# --- btergm-style block bootstrap over the 7 transitions ----------------\n")
cat(sprintf("boot_std_errors = [%s]\n", num(boot_se)))
cat("# The same bootstrap under five further seeds, disagreeing with itself.\n")
cat(sprintf("boot_se_seed_sd = [%s]\n", num(boot_se_sd)))
cat(sprintf("boot_se_seed_mean = [%s]\n", num(colMeans(boot_reps))))
cat("\n# --- the boundary panel, frozen ------------------------------------------\n")
cat(sprintf("boundary_n_actors = %d\n", b_n))
cat(sprintf("boundary_n_waves = %d\n", b_waves))
cat(sprintf("boundary_grp = [%s]\n", strs(b_grp)))
cat(sprintf("boundary_edge_counts = [%s]\n", paste(sapply(b_mats, sum), collapse = ", ")))
cat(sprintf("boundary_wave_src = [%s]\n", b_edge_arrays(1)))
cat(sprintf("boundary_wave_dst = [%s]\n", b_edge_arrays(2)))
cat("# tergm AS SHIPPED. Coefficient 4 (Persist~nodematch.grp) is a point on the\n")
cat("# asymptote, NOT an assertion target; TERGM.jl reports -Inf there.\n")
cat(sprintf("boundary_term_names = [%s]\n", strs(names(b_coef))))
cat(sprintf("boundary_coefficients = [%s]\n", num(as.numeric(b_coef))))
cat(sprintf("boundary_std_errors = [%s]\n", num(as.numeric(b_se))))
cat(sprintf("boundary_warnings = [%s]\n", strs(unique(b_warnings))))
cat(sprintf("boundary_finite_index = [%s]\n", paste(b_finite, collapse = ", ")))
cat("boundary_fixed_index = 4\n")
cat("boundary_fixed_sign = -1\n")
cat(sprintf("boundary_finite_coefficients = [%s]\n", num(as.numeric(b_coef)[b_finite])))
cat(sprintf("boundary_finite_std_errors = [%s]\n", num(as.numeric(b_se)[b_finite])))
cat("# The exact limit of the pseudo-likelihood (glm at epsilon = 1e-14 on the rows\n")
cat("# the dropped statistic does not touch): what TERGM.jl reproduces.\n")
cat(sprintf("boundary_exact_finite_coefficients = [%s]\n", num(b_exact_coef)))
cat(sprintf("boundary_exact_finite_std_errors = [%s]\n", num(b_exact_se)))
cat(sprintf("boundary_cmple_vs_glm_max_abs_diff = %.17g\n", b_cmple_vs_glm))
cat(sprintf("boundary_cmple_se_vs_glm_max_abs_diff = %.17g\n", b_cmple_se_vs_glm))
cat(sprintf("boundary_loglik = %.17g\n", as.numeric(b_ll)))
cat(sprintf("boundary_dropped_loglik = %.17g\n", b_dropped_ll))
cat(sprintf("boundary_asymptote_tail = %.17g\n", b_tail))
cat("# R's logLik attributes. tergm counts all 4 coefficients (it did not drop);\n")
cat("# TERGM.jl's dof() counts the 3 finite ones and its BIC sample size is the\n")
cat("# untouched free dyads (`boundary_n_kept`), R ergm's drop convention.\n")
cat(sprintf("boundary_loglik_df = %d\n", attr(b_ll, "df")))
cat(sprintf("boundary_loglik_nobs = %d\n", attr(b_ll, "nobs")))
cat(sprintf("boundary_n_formation_rows = %d\n", nrow(b_Xf)))
cat(sprintf("boundary_n_persistence_rows = %d\n", nrow(b_Xd)))
cat(sprintf("boundary_n_kept = %d\n", nrow(b_Xf) + sum(b_keep)))
cat("\n# --- dyad-dependent CMPLE on the main panel (tergm as shipped) ------------\n")
emit_fit <- function(prefix, f) {
  cat(sprintf("%s_term_names = [%s]\n", prefix, strs(f$names)))
  cat(sprintf("%s_coefficients = [%s]\n", prefix, num(f$coef)))
  cat(sprintf("%s_std_errors = [%s]\n", prefix, num(f$se)))
  cat(sprintf("%s_loglik = %.17g\n", prefix, f$loglik))
  cat(sprintf("%s_loglik_df = %d\n", prefix, f$df))
  cat(sprintf("%s_loglik_nobs = %d\n", prefix, f$nobs))
  cat(sprintf("%s_warnings = [%s]\n", prefix, strs(f$warnings)))
}
emit_fit("dyaddep_mutual", dd_mutual)
emit_fit("dyaddep_triangle", dd_triangle)
cat("\n# --- the undirected panel, frozen (upper triangles) -----------------------\n")
cat(sprintf("undirected_n_actors = %d\n", u_n))
cat(sprintf("undirected_n_waves = %d\n", u_waves))
cat(sprintf("undirected_grp = [%s]\n", strs(u_grp)))
cat(sprintf("undirected_edge_counts = [%s]\n", paste(sapply(u_mats, function(A) sum(A[upper.tri(A)])), collapse = ", ")))
cat(sprintf("undirected_wave_src = [%s]\n", u_edge_arrays(1)))
cat(sprintf("undirected_wave_dst = [%s]\n", u_edge_arrays(2)))
emit_fit("undirected", undir)
emit_fit("undirected_kstar", undir_kstar)
cat("\n# --- expanding terms (tergm as shipped): the columns statnet resolves ------\n")
cat("# `undirected_grp3` is a second attribute on the SAME frozen undirected panel\n")
cat(sprintf("undirected_grp3 = [%s]\n", strs(u_grp3)))
emit_fit("expand_undirected", expand_undirected)
emit_fit("expand_undirected_degree", expand_undirected_degree)
emit_fit("expand_directed", expand_directed)
emit_fit("expand_directed_degree", expand_directed_degree)
