# Golden fixture: statnet `tergm` CMPLE + a btergm-style block bootstrap on a
# simulated 8-wave directed panel.
#
# Regenerate from the package root (~60s):
#
#   Rscript test/fixtures/r/panel_stergm.R > test/fixtures/panel_stergm.toml
#
# WHAT IS BEING VALIDATED, AND WHY THE PANEL IS DYAD-INDEPENDENT ON PURPOSE
#
# TERGM.jl's `stergm(...; method=:cmple)` fits a SEPARABLE model by conditional
# pseudo-likelihood: formation rows are the dyads that were non-edges at t-1
# (statistics on Y+ = Y_{t-1} u Y_t), persistence rows are the dyads that were
# edges at t-1 (statistics on Y- = Y_{t-1} n Y_t), pooled over transitions and
# maximized by logistic regression. R's `tergm(..., estimate="CMPLE")` is the
# same estimator, written by other people.
#
# The formation and persistence formulas here are edges + nodematch("grp"), which
# are DYAD-INDEPENDENT. That is deliberate, and it is what gives the fixture
# teeth: under dyad independence the conditional pseudo-likelihood IS the
# conditional likelihood, so CMPLE is the exact conditional MLE. Both packages
# maximize the same strictly-concave logistic likelihood; there is no Monte Carlo
# on either side. Agreement is asserted at 1e-6, and a failure is a BUG -- in the
# auxiliary-network construction, in the free-dyad selection, or in a change
# statistic -- not noise. A dyad-dependent formula would have bought a prettier
# model and destroyed the ability to say anything exact.
#
# The panel is generated by an explicit discrete-time separable Markov chain
# (below) rather than by tergm's simulator: with dyad-independent terms the STERGM
# transition kernel factorizes into independent per-dyad Bernoulli draws, so these
# eight waves ARE an exact draw from the model being fitted, and the generating
# code is three lines of `rbinom` rather than a second implementation whose bugs
# could cancel with the estimator's. The waves are frozen into the fixture as edge
# lists, so the Julia side fits the identical networks and re-simulates nothing.
#
# THE BLOCK BOOTSTRAP
#
# TERGM.jl's `se=:bootstrap` resamples TRANSITIONS with replacement and refits.
# That is btergm's scheme: `btergm::btergm` calls `boot(unique.time.steps,
# estimate, R = R)` -- it resamples time steps, not dyads. btergm itself cannot be
# pointed at a separable Form/Persist model (it fits a pooled, non-separable
# TERGM), so this script applies btergm's resampling scheme to the CMPLE design
# directly: draw transition indices with replacement, keep the pseudo-likelihood
# rows belonging to the drawn transitions, refit by `glm`, take the empirical
# covariance of the replicate coefficients.
#
# That means the bootstrap is run over a design matrix built in this script rather
# than inside tergm, which would be worth nothing if the design were wrong -- so
# the script CHECKS it: `cmple_vs_glm_max_abs_diff` in [values] is the largest
# discrepancy between `tergm(estimate="CMPLE")`'s coefficients and the glm's on the
# same panel. It is ~1e-9. The rows being resampled are therefore tergm's rows.
#
# A bootstrap standard error is itself a random variable: the two packages draw
# DIFFERENT resamples, and can never agree to machine precision no matter how
# correct both are. So the script reruns the entire bootstrap under five further
# seeds and freezes the seed-to-seed sd of every bootstrap SE (`boot_se_seed_sd`).
# The tolerance is a multiple of that measured width. Comparing two bootstraps any
# other way would be measuring nothing.

suppressMessages({
  .libPaths(c(path.expand("~/R/library"), .libPaths()))
  library(network)
  library(tergm)
  library(btergm)
})

seed <- 20260713
set.seed(seed)

n_actors <- 25
n_waves <- 8

# Alternating two-group attribute: 13 "a", 12 "b".
grp <- rep(c("a", "b"), length.out = n_actors)
same <- outer(grp, grp, "==")
diag(same) <- FALSE

logistic <- function(x) 1 / (1 + exp(-x))

# Separable dyad-independent STERGM transition kernel. theta_form governs whether
# a non-tie appears; theta_persist whether a tie survives. Both are
# edges + nodematch("grp").
theta_form <- c(edges = -2.2, nodematch.grp = 0.8)
theta_persist <- c(edges = 0.5, nodematch.grp = 0.9)

P_form <- logistic(theta_form[1] + theta_form[2] * same)
P_persist <- logistic(theta_persist[1] + theta_persist[2] * same)

offdiag <- which(row(matrix(0, n_actors, n_actors)) !=
                 col(matrix(0, n_actors, n_actors)))

M <- matrix(0L, n_actors, n_actors)
M[offdiag] <- rbinom(length(offdiag), 1, 0.10)   # wave 1: Bernoulli(0.10)
mats <- list(M)
for (t in 2:n_waves) {
  U <- matrix(runif(n_actors * n_actors), n_actors, n_actors)
  N <- ifelse(M == 1L, as.integer(U < P_persist), as.integer(U < P_form))
  diag(N) <- 0L
  mats[[t]] <- N
  M <- N
}

as_nw <- function(A) {
  nw <- network(A, directed = TRUE)
  nw %v% "grp" <- grp
  nw
}
nets <- lapply(mats, as_nw)

# --- (1) tergm CMPLE ---------------------------------------------------------
# tergm prints "Starting maximum pseudolikelihood estimation (MPLE)..." to stdout,
# and this script's stdout IS the TOML fixture, so unsuppressed it emits an
# unparseable file.
fit <- NULL
invisible(capture.output(
  fit <- tergm(nets ~ Form(~edges + nodematch("grp")) +
                      Persist(~edges + nodematch("grp")),
               estimate = "CMPLE", times = 1:n_waves),
  type = "output"))
cmple_coef <- coef(fit)
cmple_se <- sqrt(diag(vcov(fit)))

# --- (2) the CMPLE design, per transition, for the block bootstrap -----------
# Formation rows: dyads that were 0 at t-1. Persistence rows: dyads that were 1.
# Response is the tie at t. Predictors for edges + nodematch("grp") are (1, same),
# which under dyad independence is exactly the change statistic on Y+ / Y-.
blocks <- lapply(2:n_waves, function(t) {
  prev <- mats[[t - 1]]; cur <- mats[[t]]
  fi <- which(prev == 0 & row(prev) != col(prev))
  di <- which(prev == 1)
  list(Xf = cbind(1, as.numeric(same[fi])), yf = as.numeric(cur[fi]),
       Xd = cbind(1, as.numeric(same[di])), yd = as.numeric(cur[di]))
})

# `ctrl` is the convergence criterion. The DEFAULT (epsilon = 1e-8) is what
# tergm ships; the tight one (1e-14) pins down where the exact conditional MLE
# actually is. The difference between them turns out to matter -- see below.
fit_blocks <- function(idx, ctrl = glm.control()) {
  Xf <- do.call(rbind, lapply(idx, function(b) blocks[[b]]$Xf))
  yf <- unlist(lapply(idx, function(b) blocks[[b]]$yf))
  Xd <- do.call(rbind, lapply(idx, function(b) blocks[[b]]$Xd))
  yd <- unlist(lapply(idx, function(b) blocks[[b]]$yd))
  gf <- glm.fit(Xf, yf, family = binomial(), control = ctrl)
  gd <- glm.fit(Xd, yd, family = binomial(), control = ctrl)
  se <- function(g) sqrt(diag(chol2inv(g$qr$qr[1:g$rank, 1:g$rank, drop = FALSE])))
  list(coef = c(gf$coefficients, gd$coefficients), se = c(se(gf), se(gd)))
}

n_trans <- n_waves - 1
tight <- glm.control(epsilon = 1e-14, maxit = 200)
glm_tight <- fit_blocks(seq_len(n_trans), tight)

# THE CHECK THAT MAKES THE BOOTSTRAP MEAN ANYTHING: does the design matrix built
# in this script reproduce tergm's own CMPLE fit? If not, the bootstrap below is
# resampling the wrong rows and the fixture is worthless.
#
# It does -- and in the process it exposes something worth freezing. tergm's
# CMPLE runs R's `glm` at its DEFAULT convergence criterion (epsilon = 1e-8) and
# stops there, ~1.5e-8 short of the exact conditional MLE in the coefficients and
# ~6e-6 short in the standard errors (the SEs are the more sensitive of the two,
# being a function of the fitted probabilities). TERGM.jl runs Newton-Raphson to
# tol = 1e-8 in the gradient and lands on the EXACT optimum, reproducing the
# tightly-converged R glm to ~1e-10.
#
# So the residual disagreement between TERGM.jl and tergm on this model is
# tergm's optimizer slack, not TERGM.jl's error. Both numbers are frozen: the
# `coefficients`/`std_errors` values are tergm's as-shipped output, and the
# `exact_*` values are the same estimator taken to convergence. The Julia testset
# asserts against BOTH, tightly against the exact one.
cmple_vs_glm <- max(abs(as.numeric(cmple_coef) - glm_tight$coef))
cmple_se_vs_glm <- max(abs(as.numeric(cmple_se) - glm_tight$se))

# --- (3) btergm-style block bootstrap over transitions -----------------------
R_boot <- 400
boot_once <- function(s) {
  set.seed(s)
  reps <- t(replicate(R_boot,
                      fit_blocks(sample(seq_len(n_trans), n_trans,
                                        replace = TRUE))$coef))
  apply(reps, 2, sd)
}
boot_se <- boot_once(seed)

# How much does the bootstrap SE move when only the RESAMPLE DRAWS change?
boot_seeds <- c(101, 202, 303, 404, 505)
boot_reps <- t(sapply(boot_seeds, boot_once))
boot_se_sd <- apply(boot_reps, 2, sd)

num <- function(x) paste(sprintf("%.17g", x), collapse = ", ")
strs <- function(x) paste(sprintf('"%s"', x), collapse = ", ")
edge_arrays <- function(sel) paste(sapply(mats, function(A) {
  e <- which(A == 1L, arr.ind = TRUE)
  paste0("[", paste(e[, sel], collapse = ", "), "]")
}), collapse = ", ")

cat('name = "panel_stergm"\n\n')

cat("[provenance]\n")
cat(sprintf('r_version = "%s"\n', as.character(getRversion())))
cat(sprintf('tergm_version = "%s"\n', as.character(packageVersion("tergm"))))
cat(sprintf('btergm_version = "%s"\n', as.character(packageVersion("btergm"))))
cat(sprintf('ergm_version = "%s"\n', as.character(packageVersion("ergm"))))
cat(sprintf('network_version = "%s"\n', as.character(packageVersion("network"))))
cat(sprintf("seed = %d\n", seed))
cat('script = "test/fixtures/r/panel_stergm.R"\n')
cat(sprintf('date = "%s"\n', format(Sys.Date())))
cat('dataset = "simulated: 25 actors, 8 directed waves, alternating two-group `grp` attribute; drawn from the separable dyad-independent STERGM whose parameters are in [values].generating_* -- the waves themselves are frozen below, nothing is re-simulated in Julia"\n')
cat('model = "Form(~edges + nodematch(\\"grp\\")) + Persist(~edges + nodematch(\\"grp\\")), estimate=\\"CMPLE\\", times=1:8"\n')
cat(sprintf('bootstrap = "btergm-style block bootstrap: %d resamples of the %d transitions with replacement, refit by glm"\n', R_boot, n_trans))
cat(sprintf('bootstrap_seeds = "%s"\n', paste(boot_seeds, collapse = ",")))
cat("\n")

cat("[tolerance]\n")
cat("# CMPLE COEFFICIENTS AND STANDARD ERRORS. edges + nodematch is\n")
cat("# dyad-independent, so the conditional pseudo-likelihood IS the conditional\n")
cat("# likelihood: CMPLE is the exact conditional MLE and both packages are\n")
cat("# maximizing the same strictly-concave logistic likelihood on the same rows.\n")
cat("# No Monte Carlo, no approximation, nothing to average over. The ONLY\n")
cat("# difference two correct implementations can have here is where their\n")
cat("# optimizers stop -- and on this model that difference is measurable, and it\n")
cat("# is R's, not Julia's:\n")
cat("#\n")
cat("#   tergm's CMPLE runs R's `glm` at its default epsilon = 1e-8 and stops\n")
cat("#   there. Against the same glm taken to epsilon = 1e-14, tergm's shipped\n")
cat("#   answer is off by ~1.5e-8 in the coefficients and ~6e-6 in the standard\n")
cat("#   errors (the SEs are the more sensitive of the two, being a function of\n")
cat("#   the fitted probabilities). TERGM.jl's Newton-Raphson lands on the exact\n")
cat("#   optimum and reproduces the tightly-converged R glm to ~1e-10.\n")
cat("#\n")
cat("# So `coefficients`/`std_errors` are compared to tergm AS SHIPPED at a\n")
cat("# tolerance that covers tergm's own optimizer slack -- 1e-6 on the\n")
cat("# coefficients (60x the observed slack) and 1e-4 on the standard errors\n")
cat("# (16x the observed slack, and still 0.13% of the smallest SE in the model,\n")
cat("# far too tight for any real discrepancy to hide under). Widening the SE\n")
cat("# tolerance is not a concession: `exact_std_errors` below is the same\n")
cat("# estimator taken to convergence, and THAT is asserted at 1e-6, where\n")
cat("# TERGM.jl passes with four orders of magnitude to spare. The loose number\n")
cat("# measures R; the tight number measures Julia.\n")
cat("coefficients = 1e-6\n")
cat("std_errors = 1e-4\n")
cat("exact_coefficients = 1e-6\n")
cat("exact_std_errors = 1e-6\n")
cat("#\n")
cat("# BLOCK-BOOTSTRAP STANDARD ERRORS. A bootstrap SE is a random variable: R\n")
cat("# and Julia draw different resamples of the transitions, so they cannot\n")
cat("# agree to machine precision however correct both are. Read\n")
cat("# `boot_se_seed_sd` in [values] first -- that is THIS bootstrap, rerun under\n")
cat("# five further seeds, disagreeing with itself. With only 7 transitions to\n")
cat("# resample the block bootstrap is coarse by construction and that sd is\n")
cat("# large relative to the SE itself; no cross-implementation tolerance can\n")
cat("# sit below it. The tolerance is 3x the largest such sd, which is the\n")
cat("# honest resolution of the comparison. It is deliberately NOT used to make\n")
cat("# a claim the data cannot support: what this checks is that TERGM.jl's\n")
cat("# bootstrap SEs agree with R's to within the noise of the bootstrap itself,\n")
cat("# not that they are equal.\n")
cat("#\n")
cat("# Measured on the Julia side (mean of 5 TERGM.jl bootstraps at declared\n")
cat("# seeds, 400 resamples each): |mean(TERGM.jl) - R| = 0.0032, 0.0040,\n")
cat("# 0.0006, 0.0071. TERGM.jl's own seed-to-seed sd is 0.0023, 0.0023, 0.0009,\n")
cat("# 0.0051 -- the same order as R's. The largest gap (0.0071, on persistence\n")
cat("# nodematch) is 1.7x R's seed-to-seed sd on that SE, i.e. the two bootstraps\n")
cat("# differ by about as much as either differs from itself. Both sides are\n")
cat("# seeded, so the Julia comparison is deterministic and cannot flake.\n")
cat(sprintf("boot_std_errors = %.4g\n", 3 * max(boot_se_sd)))
cat("\n")

cat("[values]\n")
cat("# --- the panel, frozen. Julia rebuilds these exact networks. -------------\n")
cat(sprintf("n_actors = %d\n", n_actors))
cat(sprintf("n_waves = %d\n", n_waves))
cat("directed = true\n")
cat(sprintf("grp = [%s]\n", strs(grp)))
cat(sprintf("edge_counts = [%s]\n", paste(sapply(mats, sum), collapse = ", ")))
cat(sprintf("wave_src = [%s]\n", edge_arrays(1)))
cat(sprintf("wave_dst = [%s]\n", edge_arrays(2)))
cat("\n# The parameters the panel was drawn from. NOT an assertion target -- the\n")
cat("# estimator is being compared to R, not to truth -- but a sanity anchor: a\n")
cat("# fit that lands far from these on 7 transitions of 600 dyads is suspicious.\n")
cat(sprintf("generating_formation = [%s]\n", num(theta_form)))
cat(sprintf("generating_persistence = [%s]\n", num(theta_persist)))
cat("\n# --- tergm CMPLE: exact conditional MLE, compared at 1e-6 ---------------\n")
cat(sprintf("term_names = [%s]\n", strs(names(cmple_coef))))
cat(sprintf("coefficients = [%s]\n", num(as.numeric(cmple_coef))))
cat(sprintf("std_errors = [%s]\n", num(as.numeric(cmple_se))))
cat("# Formation and persistence split out, in TERGM.jl's own accessor order.\n")
cat(sprintf("formation_coefficients = [%s]\n", num(as.numeric(cmple_coef)[1:2])))
cat(sprintf("formation_std_errors = [%s]\n", num(as.numeric(cmple_se)[1:2])))
cat(sprintf("persistence_coefficients = [%s]\n", num(as.numeric(cmple_coef)[3:4])))
cat(sprintf("persistence_std_errors = [%s]\n", num(as.numeric(cmple_se)[3:4])))
cat("\n# --- the SAME estimator, taken to convergence ---------------------------\n")
cat("# R glm at epsilon = 1e-14 rather than tergm's default 1e-8. This is where\n")
cat("# the exact conditional MLE actually is, and it is what TERGM.jl reproduces\n")
cat("# (to ~1e-10). Asserted at 1e-6.\n")
cat(sprintf("exact_coefficients = [%s]\n", num(glm_tight$coef)))
cat(sprintf("exact_std_errors = [%s]\n", num(glm_tight$se)))
cat("\n# How far tergm AS SHIPPED sits from that exact optimum. This is the\n")
cat("# entire residual disagreement between TERGM.jl and tergm on this model:\n")
cat("# it is R's optimizer slack, and it is why `std_errors` above is compared\n")
cat("# at 1e-4 while `exact_std_errors` is compared at 1e-6.\n")
cat(sprintf("cmple_vs_glm_max_abs_diff = %.17g\n", cmple_vs_glm))
cat(sprintf("cmple_se_vs_glm_max_abs_diff = %.17g\n", cmple_se_vs_glm))
cat("\n# --- btergm-style block bootstrap over the 7 transitions ----------------\n")
cat(sprintf("boot_std_errors = [%s]\n", num(boot_se)))
cat("# The same bootstrap under five further seeds, disagreeing with itself.\n")
cat(sprintf("boot_se_seed_sd = [%s]\n", num(boot_se_sd)))
cat(sprintf("boot_se_seed_mean = [%s]\n", num(colMeans(boot_reps))))
