[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ERGM = "d623cd87-b018-4e2a-bf53-b77ebcdc9da2"
Network = "027a387e-e55f-4537-a155-5037e5a23bdb"
NetworkDynamic = "2ec8e4a1-edb9-4657-8cef-4d333c164b0b"
TERGM = "6fc22812-126d-4a5c-ac3d-a5f62b7af224"

[sources]
TERGM = {path = ".."}
ERGM = {url = "https://github.com/statistical-network-analysis-with-Julia/ERGM.jl.git"}
Network = {url = "https://github.com/statistical-network-analysis-with-Julia/Network.jl.git"}
NetworkDynamic = {url = "https://github.com/statistical-network-analysis-with-Julia/NetworkDynamic.jl.git"}

[compat]
Documenter = "1"
